server:
  port: 9999
spring:
  application:
    name: "@pom.artifactId@"
  activemq:
    broker-url: tcp://localhost:61616
    password: ${activemq.password}
    user: admin

---
spring:
  profiles: pro
  activemq:
    broker-url: tcp://mingzuozhibi.com:61616
