server:
  port: 9999
spring:
  application:
    name: "@pom.artifactId@"
  activemq:
    broker-url: tcp://localhost:61616
    password: ${activemq.password}
    user: admin
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_gateway_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: fuhaiwei
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.format_sql: true
    show-sql: true
  session:
    store-type: redis

---
spring:
  profiles: pro
  activemq:
    broker-url: tcp://mingzuozhibi.com:61616
  datasource:
    url: jdbc:mysql://localhost:3306/mzzb_gateway_pro?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
